# UI and visual part
MARGIN = 20
FPS = 60

# Files names
THAUM_CONTROLS_CONFIG_DIR = 'configs'
THAUM_CONTROLS_CONFIG_NAME = 'thaumControlsConfig.json'

# In-game inventory
# !!! Don't touch if you not sure !!!
INVENTORY_SLOTS_X = 9
INVENTORY_SLOTS_Y = 3
INVENTORY_SLOTS_TOTAL = INVENTORY_SLOTS_X * INVENTORY_SLOTS_Y

THAUM_ASPECTS_INVENTORY_SLOTS_X = 5
THAUM_ASPECTS_INVENTORY_SLOTS_Y = 5
THAUM_ASPECTS_INVENTORY_SLOTS_TOTAL = THAUM_ASPECTS_INVENTORY_SLOTS_X * THAUM_ASPECTS_INVENTORY_SLOTS_Y

THAUM_HEXAGONS_SLOTS_X = 11
THAUM_HEXAGONS_SLOTS_Y = 11

DELAY_BETWEEN_EVENTS = 1  # secs
