name: Auto Translate Readme  # The name of your action

on:
  push:  # Run when committing to a branch
    branches:
    - master # Set the name of your branch if required
    paths: # Start translating only if readme or this config changed in current push
    - 'README.MD'
    - 'README.md'
    - 'readme.md'
    - 'Readme.md'
    - '.github/workflows/**'

jobs:
  translate:  # Task name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # Step: code check
        uses: actions/checkout@v2  # Using an action to test the code

      - name: Run translation  # Step: start the translation
        uses: mrf0rtuna4/Github-Readme-AutoTranslator@v2.0.0  # Using an action to translate
        env:
          LANGS: 'russian,english,italian,dutch,spanish,arabic,chinese (traditional),chinese (simplified),french,hindi,korean' # List of languages to be translated
          FILES: 'README.md'

      - name: Push to GitHub  # Step: Submit changes to GitHub
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Using an action to publish to GitHub Pages
        with:
          target_branch: README_TRANSLATIONS  # The branch to which the changes will be sent
          build_dir: 'dist'  # The directory with the collected files
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN_GITHUB }}  # Transferring a GitHub access token
